--- #YAML:1.0
name:               Win32-Word-Declarative
version:            0.01
abstract:           Provide a declarative interface to Microsoft Word documents (in and out)!
author:
    - Michael Roberts <michael@vivtek.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Declarative:  0.07
    Test::More:          0
    Win32::OLE:          0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
